# Generated by Django 3.0.6 on 2020-05-10 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(choices=[('ct', 'Count'), ('cup', '1 Cup'), ('tbsp', 'TBSP'), ('tsp', 'TSP')], default='cup', max_length=100)),
                ('type', models.CharField(choices=[('poultry', 'Poultry'), ('fish', 'Fish'), ('meat', 'Meat'), ('fruit', 'Fruit'), ('vegetable', 'Vegetable'), ('starch', 'Starch'), ('other', 'Other')], max_length=25)),
                ('calories', models.FloatField()),
                ('fat', models.FloatField()),
                ('satfat', models.FloatField()),
                ('cholesterol', models.FloatField()),
                ('sodium', models.FloatField()),
                ('carbs', models.FloatField()),
                ('fiber', models.FloatField()),
                ('sugar', models.FloatField()),
                ('protein', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('winter', models.BooleanField(default=True)),
                ('spring', models.BooleanField(default=True)),
                ('summer', models.BooleanField(default=True)),
                ('fall', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=1)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dj_cookbook.Ingredient')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dj_cookbook.Meal')),
            ],
        ),
    ]
